export const SUMMARY_CARDS = [
  {
    id: 'total-assigned',
    title: 'Total Assigned',
    value: '16',
    note: 'All queued',
    tone: 'blue',
  },
  {
    id: 'high-priority',
    title: 'High Priority',
    value: '7',
    note: 'Urgent action needed',
    tone: 'red',
  },
  {
    id: 'sla-breaching',
    title: 'SLA Breaching',
    value: '3',
    note: 'Within 3 hours',
    tone: 'amber',
  },
];

/* The four stages an application moves through on the agent-1 panel. `stage` on
   a row is the 1-based step it currently sits on. */
export const APPLICATION_STEPS = [
  'Assigned',
  'Verification Started',
  'Decision Made',
  'Forwarded to A2',
];

/* Verification checklist, in the order it is shown. Each row carries its own
   `checklist` array of booleans-by-id; this is the label source. */
export const CHECKLIST_ITEMS = [
  { id: 'identity', label: 'Identity Verified' },
  { id: 'property', label: 'Property Verified' },
  { id: 'payment', label: 'Payment Verified' },
  { id: 'signature', label: 'Signature Verified' },
  { id: 'supporting', label: 'Supporting Docs Verified' },
  { id: 'complete', label: 'Application Complete' },
];

export const QUEUE_ROWS = [
  {
    id: 'APP-2024-00418',
    initials: 'RK',
    name: 'Rajesh Kumar',
    department: 'Revenue',
    service: 'Property Tax',
    priority: 'High',
    priorityTone: 'high',
    status: 'Assigned',
    statusTone: 'assigned',
    time: '6h 00m',
    stage: 1,
    appliedDate: '02 Jul 2024',
    assignedAt: '09:00 AM',
    applicant: {
      fullName: 'Rajesh Kumar',
      mobile: '+91 98765 43210',
      email: 'rajesh.kumar@email.com',
      address: '14/2, Gandhi Nagar, Bengaluru - 560001',
    },
    property: {
      surveyNo: 'SY-1247/3B',
      plotNo: 'Plot 42, Sector 7',
      totalArea: '240 sq.m',
      builtUpArea: '180 sq.m',
      propertyType: 'Residential',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹12,400',
      dueDate: '10 Jul 2024',
      mode: 'Online',
    },
    verified: ['identity', 'property'],
    documents: [
      { id: 'aadhaar', title: 'Aadhaar Card', category: 'Identity', size: '1.2 MB', date: '02 Jul 2024', status: 'approved' },
      { id: 'pan', title: 'PAN Card', category: 'Identity', size: '0.8 MB', date: '02 Jul 2024', status: 'approved' },
      { id: 'plan', title: 'Property Plan', category: 'Property', size: '3.4 MB', date: '02 Jul 2024', status: 'pending' },
      { id: 'receipt', title: 'Property Tax Receipt', category: 'Property', size: '0.5 MB', date: '02 Jul 2024', status: 'pending' },
      { id: 'sitemap', title: 'Site Map', category: 'Property', size: '2.1 MB', date: '01 Jul 2024', status: 'rejected' },
      { id: 'encumbrance', title: 'Encumbrance Certificate', category: 'Legal', size: '1.7 MB', date: '01 Jul 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application Submitted', time: '28 Jun 2024 at 10:32 AM', actor: 'Citizen Self', detail: 'Application filed online via eCitizen portal', status: 'completed' },
      { id: 'assigned', title: 'Assigned to Agent 1', time: '29 Jun 2024 at 09:00 AM', actor: 'System Auto', detail: 'Auto-assigned based on department workload', status: 'completed' },
      { id: 'started', title: 'Verification Started', time: '01 Jul 2024 at 10:15 AM', actor: 'Ravi Kumar (A1)', detail: 'Document review initiated', status: 'completed' },
      { id: 'query', title: 'Query Raised', time: '01 Jul 2024 at 03:20 PM', actor: 'Ravi Kumar (A1)', detail: 'Site map is unclear — customer to re-upload', status: 'completed' },
      { id: 'reupload', title: 'Customer Re-uploaded', time: '02 Jul 2024 at 11:05 AM', actor: 'Rajesh Kumar', detail: 'Updated site map uploaded', status: 'active' },
      { id: 'approval', title: 'Pending Final Approval', time: '— at —', actor: '—', detail: 'Awaiting officer decision', status: 'pending' },
    ],
    notes: [
      { id: 'note-1', title: 'Internal note', detail: 'Cross-check the ownership document before final approval.', time: '02 Jul 2024 · 09:20 AM' },
    ],
    messages: [
      { id: 'msg-1', title: 'Citizen', detail: 'I have uploaded the revised property plan as requested.', time: '02 Jul 2024 · 10:05 AM' },
    ],
  },
  {
    id: 'APP-2024-00423',
    initials: 'DM',
    name: 'Deepak Mishra',
    department: 'Revenue',
    service: 'Property Tax',
    priority: 'Medium',
    priorityTone: 'medium',
    status: 'Assigned',
    statusTone: 'assigned',
    time: '1d 6h',
    stage: 1,
    appliedDate: '30 Jun 2024',
    assignedAt: '11:30 AM',
    applicant: {
      fullName: 'Deepak Mishra',
      mobile: '+91 98112 33894',
      email: 'deepak.mishra@email.com',
      address: 'Flat 9A, Harmony Heights, Bengaluru - 560037',
    },
    property: {
      surveyNo: 'SY-0982/1A',
      plotNo: 'Plot 9, Sector 3',
      totalArea: '145 sq.m',
      builtUpArea: '120 sq.m',
      propertyType: 'Apartment',
      zone: 'Zone B – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹8,250',
      dueDate: '08 Jul 2024',
      mode: 'UPI',
    },
    verified: ['identity'],
    documents: [
      { id: 'receipt', title: 'Tax Receipt', category: 'Payment', size: '0.4 MB', date: '30 Jun 2024', status: 'approved' },
      { id: 'ownership', title: 'Ownership Proof', category: 'Property', size: '1.0 MB', date: '30 Jun 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application submitted', detail: 'Submitted through the citizen portal', time: '30 Jun 2024 · 10:40 AM' },
      { id: 'assigned', title: 'Assigned to you', detail: 'Auto-assigned from the Revenue queue', time: '30 Jun 2024 · 11:30 AM' },
    ],
    notes: [],
    messages: [],
  },
  {
    id: 'APP-2024-00420',
    initials: 'AV',
    name: 'Anand Verma',
    department: 'Revenue',
    service: 'Encumbrance Cert',
    priority: 'Medium',
    priorityTone: 'medium',
    status: 'Pending Verification',
    statusTone: 'pending',
    time: '6h 00m',
    stage: 2,
    appliedDate: '03 Jul 2024',
    assignedAt: '10:15 AM',
    applicant: {
      fullName: 'Anand Verma',
      mobile: '+91 99887 22145',
      email: 'anand.verma@email.com',
      address: 'B-204, Lotus Homes, Bengaluru - 560068',
    },
    property: {
      surveyNo: 'SY-3311/2C',
      plotNo: 'Plot 18, Sector 11',
      totalArea: '310 sq.m',
      builtUpArea: '210 sq.m',
      propertyType: 'Villa',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹3,100',
      dueDate: '11 Jul 2024',
      mode: 'Online',
    },
    verified: ['identity', 'supporting'],
    documents: [
      { id: 'deed', title: 'Sale Deed', category: 'Legal', size: '2.1 MB', date: '03 Jul 2024', status: 'pending' },
      { id: 'mutation', title: 'Mutation Order', category: 'Legal', size: '0.6 MB', date: '03 Jul 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application submitted', detail: 'Submitted through the citizen portal', time: '03 Jul 2024 · 09:05 AM' },
      { id: 'started', title: 'Verification started', detail: 'Documents opened for review', time: '03 Jul 2024 · 10:15 AM' },
    ],
    notes: [
      { id: 'note-1', title: 'Internal note', detail: 'Awaiting clarification on the encumbrance period.', time: '03 Jul 2024 · 12:00 PM' },
    ],
    messages: [],
  },
  {
    id: 'APP-2024-00426',
    initials: 'AJ',
    name: 'Arun Joshi',
    department: 'Urban Dev',
    service: 'Zone Certificate',
    priority: 'High',
    priorityTone: 'high',
    status: 'Verification Started',
    statusTone: 'started',
    time: '2h 30m',
    stage: 2,
    appliedDate: '04 Jul 2024',
    assignedAt: '08:45 AM',
    applicant: {
      fullName: 'Arun Joshi',
      mobile: '+91 97531 66774',
      email: 'arun.joshi@email.com',
      address: 'Plot 42, Sector 7, Bengaluru - 560102',
    },
    property: {
      surveyNo: 'SY-7742/5D',
      plotNo: 'Plot 42, Sector 7',
      totalArea: '480 sq.m',
      builtUpArea: '360 sq.m',
      propertyType: 'Commercial',
      zone: 'Zone C – Mixed',
    },
    payment: {
      status: 'Received',
      amount: '₹9,600',
      dueDate: '06 Jul 2024',
      mode: 'Net Banking',
    },
    verified: ['identity', 'property', 'payment'],
    documents: [
      { id: 'layout', title: 'Site Layout', category: 'Planning', size: '2.8 MB', date: '04 Jul 2024', status: 'approved' },
      { id: 'noc', title: 'No Objection', category: 'Planning', size: '0.9 MB', date: '04 Jul 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application submitted', detail: 'Submitted through the citizen portal', time: '04 Jul 2024 · 08:00 AM' },
      { id: 'started', title: 'Verification started', detail: 'Site review scheduled', time: '04 Jul 2024 · 08:45 AM' },
    ],
    notes: [],
    messages: [
      { id: 'msg-1', title: 'Citizen', detail: 'Please confirm the site visit slot for this week.', time: '04 Jul 2024 · 09:30 AM' },
    ],
  },
  {
    id: 'APP-2024-00427',
    initials: 'NG',
    name: 'Nisha Gupta',
    department: 'Registration',
    service: 'Sale Deed',
    priority: 'Low',
    priorityTone: 'low',
    status: 'Pending Verification',
    statusTone: 'pending',
    time: '1d 4h',
    stage: 2,
    appliedDate: '01 Jul 2024',
    assignedAt: '02:10 PM',
    applicant: {
      fullName: 'Nisha Gupta',
      mobile: '+91 98322 11890',
      email: 'nisha.gupta@email.com',
      address: 'North Avenue, Pearl Lane, Bengaluru - 560045',
    },
    property: {
      surveyNo: 'SY-5108/4B',
      plotNo: 'Plot 7, Pearl Lane',
      totalArea: '200 sq.m',
      builtUpArea: '—',
      propertyType: 'Plot',
      zone: 'Zone B – Urban',
    },
    payment: {
      status: 'Pending',
      amount: '₹5,750',
      dueDate: '12 Jul 2024',
      mode: 'Online',
    },
    verified: ['identity'],
    documents: [
      { id: 'identity', title: 'Identity Proof', category: 'Legal', size: '0.7 MB', date: '01 Jul 2024', status: 'approved' },
      { id: 'agreement', title: 'Agreement Copy', category: 'Legal', size: '1.3 MB', date: '01 Jul 2024', status: 'pending' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application submitted', detail: 'Submitted through the citizen portal', time: '01 Jul 2024 · 01:20 PM' },
      { id: 'started', title: 'Verification started', detail: 'Waiting for legal clearance', time: '01 Jul 2024 · 02:10 PM' },
    ],
    notes: [],
    messages: [],
  },
  {
    id: 'APP-2024-00419',
    initials: 'PS',
    name: 'Priya Sharma',
    department: 'Urban Dev',
    service: 'Building Plan',
    priority: 'High',
    priorityTone: 'high',
    status: 'Waiting Customer',
    statusTone: 'waiting',
    time: '4h 30m',
    stage: 2,
    appliedDate: '04 Jul 2024',
    assignedAt: '10:00 AM',
    applicant: {
      fullName: 'Priya Sharma',
      mobile: '+91 98811 34560',
      email: 'priya.sharma@email.com',
      address: 'Apt 21, River View, Bengaluru - 560016',
    },
    property: {
      surveyNo: 'SY-2290/8A',
      plotNo: 'Plot 21, River View',
      totalArea: '265 sq.m',
      builtUpArea: '190 sq.m',
      propertyType: 'Residential',
      zone: 'Zone A – Urban',
    },
    payment: {
      status: 'Received',
      amount: '₹16,900',
      dueDate: '07 Jul 2024',
      mode: 'UPI',
    },
    verified: ['identity', 'payment'],
    documents: [
      { id: 'elevation', title: 'Building Elevation', category: 'Planning', size: '3.1 MB', date: '04 Jul 2024', status: 'rejected' },
      { id: 'floor', title: 'Floor Plan', category: 'Planning', size: '1.8 MB', date: '04 Jul 2024', status: 'approved' },
    ],
    timeline: [
      { id: 'submitted', title: 'Application submitted', detail: 'Submitted through the citizen portal', time: '04 Jul 2024 · 09:10 AM' },
      { id: 'started', title: 'Verification started', detail: 'Resubmission requested from the citizen', time: '04 Jul 2024 · 10:00 AM' },
    ],
    notes: [
      { id: 'note-1', title: 'Agent note', detail: 'Elevation drawing does not match the approved setback.', time: '04 Jul 2024 · 11:15 AM' },
    ],
    messages: [
      { id: 'msg-1', title: 'Citizen', detail: 'Revised elevation will be uploaded by tomorrow.', time: '04 Jul 2024 · 11:40 AM' },
    ],
  },
];
